### PR TITLE
Updated flexmark-all with version 0.28.0 for 1.x

### PR DESCRIPTION
**Pull request by javadev**

### CODE REVIEW

**Comment by javadev** [comment]
We need to fix this dependency for version 1.x

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<script/>
<!--  This module was also published with a richer model, Gradle metadata,   -->
<!--  which should be used instead. Do not delete the following line which   -->
<!--  is to indicate to Gradle or any Gradle module metadata file consumer   -->
<!--  that they should prefer consuming it instead.  -->
<!--  do_not_remove: published-with-gradle-metadata  -->
<modelVersion>4.0.0</modelVersion>
<groupId>org.jdrupes.mdoclet</groupId>
<artifactId>doclet</artifactId>
<version>1.0.10</version>
<dependencies>
**<dependency>
<groupId>com.vladsch.flexmark</groupId>
<artifactId>flexmark-all</artifactId>
<version>0.15.3</version>
<scope>compile</scope>
</dependency>**
</dependencies>
<name>mdoclet</name>
<description>A doclet for processing javadoc comments written with Markup</description>
<url>https://github.com/mnlipp/jdrupes-mdoclet</url>
<scm>
<url>scm:git@github.com:mnlipp/jdrupes-mdoclet.git</url>
<connection>scm:git@github.com:mnlipp/jdrupes-mdoclet.git</connection>
<developerConnection>git@github.com:mnlipp/jdrupes-mdoclet.git</developerConnection>
</scm>
<licenses>
<license>
<name>AGPL 3.0</name>
<url>https://www.gnu.org/licenses/gpl-3.0.en.html</url>
<distribution>repo</distribution>
</license>
</licenses>
<developers>
<developer>
<id>mnlipp</id>
<name>Michael N. Lipp</name>
</developer>
</developers>
</project>
```

**Comment by mnlipp** [comment]
Applied to branch 1x-maintenance, but won't compile with Java 8 because flexmark 0.64.0 uses class version 55.0, while 0.52 is expected.

**Comment by javadev** [comment]
I found version 0.62.2 uses java 8

https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-java/0.62.2/flexmark-java-0.62.2.pom

**Comment by mnlipp** [comment]
Latest compatible flexmark version is 0.28.0. After this, there are incompatible API changes.

**Comment by mnlipp** [comment]
Released.

**Pull request merged**
